# Generated by Django 5.1.4 on 2025-01-26 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='title',
            field=models.CharField(default='Untitled Activity', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placementactivity',
            name='activity_type',
            field=models.CharField(choices=[('project', 'Project Submission'), ('certification', 'Certification'), ('competition', 'Competition'), ('research', 'Research Paper'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placementactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='placementactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='domains',
            field=models.ManyToManyField(related_name='users', to='profiles.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='domains',
            field=models.ManyToManyField(related_name='projects', to='profiles.domain'),
        ),
    ]
