# Generated by Django 5.1.4 on 2025-02-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_total_points_customuser_total_activity_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_activities', to='profiles.customuser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.customuser'),
        ),
    ]
