# Generated by Django 5.1.4 on 2025-02-09 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='points',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='activity',
            name='experience_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('volunteer', 'Volunteer Work'), ('research', 'Research'), ('course', 'Course'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
