# Generated by Django 5.1.4 on 2025-02-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='domain',
            new_name='domains',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='domain',
        ),
        migrations.AddField(
            model_name='customuser',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.domain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(choices=[('FINANCE', 'Finance'), ('CONSULTING', 'Consulting'), ('RESEARCH', 'Research'), ('DATA_ANALYSIS', 'Data Analysis'), ('GENERAL', 'General')], max_length=50, unique=True),
        ),
    ]
