# Generated by Django 5.1.4 on 2025-02-09 20:14

from django.db import migrations

def add_initial_domains(apps, schema_editor):
    Domain = apps.get_model('accounts', 'Domain')
    domains = [
        "Finance",
        "Research",
        "Consulting",
        "Data Science and Analytics",
        "General"
    ]
    for domain in domains:
        Domain.objects.create(name=domain)
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_activity_options_remove_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_domains),
    ]
