# Generated by Django 5.1.4 on 2025-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_title_activity_company_activity_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='experience_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('volunteer', 'Volunteer Work'), ('research', 'Research'), ('course', 'Course'), ('project', 'Project'), ('work', 'Job'), ('freelance', 'Freelance Work'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
