# Generated by Django 5.1.4 on 2025-02-12 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Resume'),
        ),
    ]
