# Generated by Django 5.1.4 on 2025-02-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['date_joined', 'username'], 'verbose_name_plural': 'Custom Users'},
        ),
    ]
